import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex">
        <div className="relative bg-black w-[50%] custom-shape h-screen overflow-hidden">
          {/* <p className="text-3xl mx-[120px] text-[#F2A5B4] mt-10 tracking-tighter">
            Mehran Shiraz
          </p> */}
          <img
            src="/portfolio/Group 50.svg"
            alt="image"
            className="mx-[120px] mt-10 "
          />
          <img
            src="/portfolio/image1.svg"
            alt="image"
            className="max-h-full mx-[120px] "
          />
          <div className="flex absolute bottom-16 left-[15%]">
            <div className="border-2 border-white w-10 h-10 rounded-full flex justify-center items-center mx-2">
              <img src="/Vector (3).png" alt="image" className="w-2" />
            </div>
            <div className="border-2 border-white w-10 h-10 rounded-full flex justify-center items-center">
              <img src="/Vector (4).png" alt="image" className="w-3" />
            </div>
            <div className="border-2 border-white w-10 h-10 rounded-full flex justify-center items-center mx-2">
              <img src="/Vector (5).png" alt="image" className="w-3" />
            </div>
            <div className="border-2 border-white w-10 h-10 rounded-full flex justify-center items-center">
              <img src="/Vector (6).png" alt="image" className="w-2" />
            </div>
          </div>
        </div>
        <div className="bg-white w-[50%] flex items-center">
          <div className="w-[380px] mx-[50px]">
            <p className="font-medium text-[#FF0000] text-xl tracking-widest my-3">
              Hello I’m
            </p>
            <h1 className=" text-4xl font-bold">Mehran Shiraz</h1>
            <h3 className="font-medium text-base text-[#333232] uppercase my-5">
              Sr.Full Stack Developer
            </h3>
            <p className="font-medium text-base text-[#333232]">
              Grounded and solution-oriented Web Developer with a wide variety
              of professional experience and highly skilled with a strong
              groundwork in programming.Solid track record of architecting
              solutions that exceed clients expectations.
            </p>
            <Link href={"/portfolio"}>
              <button className="mt-5 bg-black text-[#FF0000] font-bold px-3 py-2 text-lg rounded-xl">
                Hire Me
              </button>
            </Link>
          </div>
        </div>
      </div>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
